name: Build ESAPI Script - v15.6

on:
  workflow_dispatch:
    inputs:
      dateInput:
        description: 'Expiration Date'
        required: true
        default: '7/11/2022'

jobs:
  build:
    runs-on: windows-2019
    env:
      GITHUB_WORKSPACE_PACKAGES_PATH: packages\ESAPI.15.6.0\lib\net45\
      PROJECT_NAME: Doserate Editor
      MAJOR_VERSION: 2
      MINOR_VERSION: 5
      PATCH_VERSION: 6
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Update AssemblyInfo.cs
      id: update_assembly_info
      run: |
        .\.github\workflows\Update-AssemblyInfo.ps1 `
          -AssemblyInfoFilePath ${{ github.workspace }}\gridScripts\MAAS-SFRThelper\Projects\MAAS-SFRThelper\Properties\AssemblyInfo.cs `
          -ExpirationDate "${{ github.event.inputs.dateInput }}" `
          -MajorVersion ${{ env.MAJOR_VERSION }} `
          -MinorVersion ${{ env.MINOR_VERSION }} `
          -PatchVersion ${{ env.PATCH_VERSION }} `
          -BuildNumber ${{ env.BUILD_NUMBER }}
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.6
      with:
        nuget-version: latest



    - name: Add VIC GitHub NuGet repository
      run: nuget source add -Name github `
        -Source "https://nuget.pkg.github.com/Varian-Innovation-Center/index.json" `
        -UserName craman96 `
        -Password ${{ secrets.ESAPI_READ_TOKEN }} `
        -StorePasswordInClearText

    - name: Download nuget package
      run: nuget install ESAPI -Version 15.6.0 -OutputDirectory packages

    - name: Update hint paths in the csproj file
      run: .\.github\workflows\Update-EsapiHintPaths.ps1 -CsprojFilePath ./DoseRateEditor -CsprojFileName DoseRateEditor.csproj 

    - name: Build Solution
      run: msbuild.exe DoseRateEditor.sln /nologo /nr:false /p:DeleteExistingFiles=True /p:Configuration=Debug /p:Platform="Any CPU"
        
    - name: Zip
      run: |
        Compress-Archive `
          -Path "${{ github.workspace }}\DoseRateEditor\bin\Debug\*" `
          -DestinationPath "${{ github.workspace }}/${{ steps.update_assembly_info.outputs.RELEASE_FILE_NAME }}-EclipseV156.zip"
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ steps.update_assembly_info.outputs.RELEASE_NAME }}-EclipseV15.6
        tag_name: ${{ steps.update_assembly_info.outputs.RELEASE_NAME }}-EclipseV15.6
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
        body: |
          # ${{ env.PROJECT_NAME }} - V${{ steps.update_assembly_info.outputs.RELEASE_VERSION }}
          This is an official release of the **`${{ env.PROJECT_NAME }}`** project.
          Supported Eclipse version: `v15.6`.
          The generated dll is valid until `${{ github.event.inputs.dateInput }}`.
        files: ${{ github.workspace }}/${{ steps.update_assembly_info.outputs.RELEASE_FILE_NAME }}-EclipseV156.zip
